services:
  nginx:
    container_name: nginx-my-azevedo
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    networks:
      - blog-network
  app:
    container_name: php-my-azevedo
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    networks:
      - blog-network

networks:
  blog-network: 
    driver: bridge
